### ISSUE TITLE
Unable to lock file: lock.pid

### ISSUE THREAD

**Issue by opensourcer2** [rllola/ZeronetBrowser#127]
I got the error 
`Unable to lock file: [Errno 2] No such file or directory: '<working directory>/ZeroNet/lock.pid'`
I used the debian package.

**Comment by rllola** [comment]
Are you using the latest version (v0.2.5)? It should have created a lock.pid file in the $HOME/.zeronet/ folder. 

Or you can try to create an empty lock.pid file in the <working directory>/ZeroNet/ folder. It might do the trick.

**Comment by opensourcer2** [comment]
I am using v0.2.5.  But no `lock.pid` file is created in `$HOME/.zeronet/ folder`.  The only place I found in code that suppose to create this file is in the debian `postinst` script.  But this can't be correct because $HOME in this script would mean the root user.

**Comment by rllola** [comment]
What system do you use? And could you tell me what is in your `zeronet.conf`?

It should have a line with your `data_dir` path.

**Comment by opensourcer2** [comment]
I am on Ubuntu 18.04.  I don't see a `zeronet.conf` file.

**Comment by rllola** [comment]
I am also on Ubuntu 18.04 and it created the `$HOME/.zeronet`  folder correctly. Can you try again to install it with this command `sudo dpkg -i ZeronetBrowser_v0.2.5_i386.deb` ?

Regarding the `$HOME` in the `postinst` script does give me `/home/lola` and not the root folder. I am not sure what I am missing here...

**Comment by opensourcer2** [comment]
Ok.  This error is gone and `$HOME/.zeronet` folder is created after I reinstalled using `sudo dpkg -i` and start it from the application menu (does not run if started from terminal, it shows some other error).  However, the homepage of zeronet still does not load (it said site can’t be reached).  The first time I installed using the GUI (gdebi-gtk) by double clicking on the `.deb` file which did not complete successfully, but no error was shown so I assumed it was ok.  So for some reason this `.deb` file cannot be successfully installed by double clicking.

The current recommended way to build debian package is to use `debuild`.  Is there any reason you build with `dpkg` instead?

**Comment by rllola** [comment]
Cool. I haven't tested using the GUI. I will look into it.

No particular reason for using `dpkg` and there is definitely room for improvement. I will look into `debuild` too. See if we can switch to it.

I think it is normal the home page is not showing. It need to be downloaded. The `.zeronet` folder is empty.

**Comment by rllola** [comment]
The next release should fix the issue with the GUI.

https://github.com/rllola/ZeronetBrowser/pull/130
