### ISSUE TITLE
Error when initializing on Windows

### ISSUE THREAD

**Issue by DaniellMesquita** [rllola/ZeronetBrowser#28]
> [9080] LOADER: Running launch.py
> Traceback (most recent call last):
>   File "launch.py", line 5, in <module>
>   File "C:\Python27-x64\Lib\site-packages\PyInstaller\loader\pyimod03_importers.
> py", line 395, in load_module
>   File "MainWindow.py", line 1, in <module>
>   File "C:\Python27-x64\Lib\site-packages\PyInstaller\loader\pyimod03_importers.
> py", line 395, in load_module
>   File "Browser.py", line 4, in <module>
> ImportError: No module named QtWebKitWidgets
> [9080] Failed to execute script launch
> [9080] LOADER: OK.
> [9080] LOADER: Cleaning up Python interpreter.

**Comment by rllola** [comment]
Could you give me the version you used ?

**Comment by DaniellMesquita** [comment]
After updating to version 0.1.4, there is another error:
> Traceback (most recent call last):
>   File "launch.py", line 6, in <module>
> ImportError: No module named ZeroNet
> [3276] Failed to execute script launch
> [3276] LOADER: OK.
> [3276] LOADER: Cleaning up Python interpreter.

**Comment by rllola** [comment]
@DaniellMesquita The new build should work smoothly. 
https://github.com/rllola/ZeronetBrowser/releases/tag/v0.1.5

Let me know if you encounter more issues.
