### ISSUE TITLE
App stopping to work, and can't find qt engine .exe

### ISSUE THREAD

**Issue by DaniellMesquita** [rllola/ZeronetBrowser#47]
![image](https://user-images.githubusercontent.com/6765277/49121830-16214f80-f299-11e8-8d53-748f62b23662.png)

**Comment by rllola** [comment]
Thanks for reporting.

I have made a big mistake. I am working locally with `Qt 5.9` and build using `Qt 5.10.1` and apparently `Qt 5.10.1` has issue with `qt.conf` file. It doesn't read it correctly. I am trying to build `Qt 5.11.2` which should work. 

Sorry, I should no better that consistency is needed to avoid headache. I will let you knoow when it is fix.

**Comment by rllola** [comment]
Ok this new release should do the trick. Could you test it for me ?
https://github.com/rllola/ZeronetBrowser/releases/tag/v0.1.6

**Comment by DaniellMesquita** [comment]
Thanks, now it loaded
![image](https://user-images.githubusercontent.com/6765277/49297687-8b13a580-f4a2-11e8-8117-fc07e5bda91f.png)
But it is slow on start, and isn't loading home page

**Comment by rllola** [comment]
Yes I force it to sleep 5 seconds before opening the windows to be sure ZeroNet has started (I will fix that).

Even when you press 'home' or enter an url ?

**Comment by DaniellMesquita** [comment]
> Even when you press 'home' or enter an url ?
Yes

**Comment by rllola** [comment]
Ok.
Let's see if this one works : https://github.com/rllola/ZeronetBrowser/releases/download/v0.1.7/build-windows.zip

**Comment by DaniellMesquita** [comment]
Error (maybe when ZeroNet is already running:
![image](https://user-images.githubusercontent.com/6765277/49667205-8a01eb80-fa41-11e8-8402-73cc0a6930a1.png)

**Comment by DaniellMesquita** [comment]
Even when ZeroNet isn't openned:
![image](https://user-images.githubusercontent.com/6765277/49667312-d0efe100-fa41-11e8-9fa8-9382f1cb5eb1.png)

**Comment by rllola** [comment]
@DaniellMesquita 
Ok that time it should be fixed : https://github.com/rllola/ZeronetBrowser/releases/tag/v0.1.8
