### ISSUE TITLE
This app can't run on your PC

### ISSUE THREAD

**Issue by bitcoren** [rllola/ZeronetBrowser#99]
Windows 10 LTSB 2016 x64
ZeronetBrowser_v0.2.3_setup.exe
The Zeronet Browser ShortCut was created to "C:\Tools\Zeronet Browser\ZeronetBrowser_v0.2.3_setup.exe"
![1](https://user-images.githubusercontent.com/38252897/57164005-54f99980-6e25-11e9-8605-2e56c79e0d96.png)
Zeronet Browser is Not starting
![2](https://user-images.githubusercontent.com/38252897/57164090-98540800-6e25-11e9-90f5-4e81321c2373.png)
 "C:\Tools\Zeronet Browser\ZeronetBrowser_v0.2.3_setup.exe" = 0 bytes
Will i need to install python 3?
ZeronetBrowser.exe does not open any browser.

**Comment by rllola** [comment]
Hey,

So you don't need to install anything. All you need is in the app. The `ZeronetBrowser_v0.2.3_setup.exe` is an installer, have you tried to run it ? It will extract the app in the your programs folder and create the needed folder in your AppData folder.

Also the application is not signed so you might have a warning message. I am looking into it.

**Comment by rllola** [comment]
I haven't heard back so I am closing this issue.

**Comment by rllola** [comment]
I have found the problem and indeed gave the wrong name to the shortcut. The next release (v0.2.6) should fix this.

Sorry it took me so long. I am not using windows.
